const scenarios = [
  { title: "VPN triage", sub: "Service status + device diagnostics", prompt: "VPN trên LT-204 lỗi; kiểm tra cả trạng thái VPN production và máy đó." },
  { title: "Missing asset", sub: "Ask safely when ID is missing", prompt: "Kiểm tra Wi-Fi trên laptop của mình giúp nhé." },
  { title: "Account lookup", sub: "Directory record and assigned devices", prompt: "Tra cứu tài khoản nhân viên EMP-1003 và thiết bị được cấp." },
  { title: "Policy evidence", sub: "Grounded internal policy answer", prompt: "Theo policy IT, tạo ticket có cần xác nhận của người dùng không?" },
  { title: "Ticket boundary", sub: "Confirmation required before action", prompt: "Tạo ticket mức high cho lỗi VPN trên LT-204 giúp mình." }
];

const state = { history: [], conversationId: null, busy: false, events: 0 };
const $ = (id) => document.getElementById(id);
const escape = (value) => String(value ?? "").replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[character]));

function scrollConversation() { const messages = $("messages"); messages.scrollTop = messages.scrollHeight; }
function setupScenarios() { const list = $("scenarioList"); scenarios.forEach((item) => { const button = document.createElement("button"); button.className = "scenario"; button.innerHTML = `<span class="scenario-title">${escape(item.title)}</span><span class="scenario-sub">${escape(item.sub)}</span>`; button.onclick = () => { document.querySelectorAll(".scenario").forEach((element) => element.classList.remove("active")); button.classList.add("active"); $("messageInput").value = item.prompt; $("messageInput").focus(); }; list.append(button); }); }
function setArtifact(artifact) { if (artifact?.artifact_version) document.title = `Northstar Helpdesk · ${artifact.artifact_version}`; }
function addMessage(role, text) { const welcome = document.querySelector(".welcome"); if (welcome) welcome.remove(); const element = document.createElement("article"); element.className = `message ${role}`; const label = role === "user" ? "YOU" : "NORTHSTAR AGENT"; let content = text; if (role === "assistant") { try { content = JSON.parse(text).reply || text; } catch {} } element.innerHTML = `<span class="message-label">${label}</span>${escape(content)}`; $("messages").append(element); scrollConversation(); }
function trace(round, title, status, detail, data, kind = "done") { const card = document.createElement("article"); card.className = `trace-card ${kind}`; card.innerHTML = `<div class="trace-meta"><span>ROUND ${round || "·"}</span><span class="trace-state">${escape(status)}</span></div><div class="trace-body"><h3>${escape(title)}</h3>${detail ? `<p>${escape(detail)}</p>` : ""}${data ? `<pre>${escape(JSON.stringify(data, null, 2))}</pre>` : ""}</div>`; $("traceStream").append(card); state.events += 1; $("traceCount").textContent = `Live process · ${state.events} event${state.events === 1 ? "" : "s"}`; scrollConversation(); }
function reset() { state.history = []; state.conversationId = null; state.events = 0; $("messages").innerHTML = '<div class="welcome"><div class="welcome-icon">✦</div><h3>Ready when you are.</h3><p>Ask about services, devices, users, policy or tickets.<br>Every action will appear in this conversation as it happens.</p></div><div class="trace-stream" id="traceStream"></div>'; $("traceCount").textContent = "Ready"; document.querySelectorAll(".scenario").forEach((element) => element.classList.remove("active")); }
async function send(message) { if (state.busy || !message.trim()) return; state.busy = true; $("sendButton").disabled = true; $("livePill").textContent = "RUNNING"; $("livePill").classList.add("running"); addMessage("user", message); $("messageInput").value = ""; trace(1, "Request accepted", "QUEUED", "Sending the conversation to the live provider.", null, "running"); try { const response = await fetch("/api/chat", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message, history: state.history, provider: "openai", conversation_id: state.conversationId }) }); if (!response.ok) throw new Error((await response.json()).detail || "Unable to start the agent."); const reader = response.body.getReader(); const decoder = new TextDecoder(); let buffer = ""; while (true) { const { value, done } = await reader.read(); if (done) break; buffer += decoder.decode(value, { stream: true }); const lines = buffer.split("\n"); buffer = lines.pop(); for (const line of lines) if (line) handle(JSON.parse(line), message); } } catch (error) { trace(null, "Provider error", "ERROR", error.message, null, "error"); addMessage("assistant", "Mình chưa thể hoàn thành yêu cầu do provider error. Hãy kiểm tra cấu hình và thử lại."); } finally { state.busy = false; $("sendButton").disabled = false; $("livePill").textContent = "LIVE"; $("livePill").classList.remove("running"); $("messageInput").focus(); } }
function handle(event, message) { if (event.type === "connected") { state.conversationId = event.conversation_id; setArtifact(event.artifact); $("modelLabel").textContent = `${event.provider} · ${event.model}`; return; } if (event.type === "round_started") return trace(event.round, "Model is assessing the request", "THINKING", "Selecting the safest next action.", null, "running"); if (event.type === "model_response" && event.tool_calls?.length) return trace(event.round, "Tool plan selected", "PLANNED", `${event.tool_calls.length} tool call${event.tool_calls.length === 1 ? "" : "s"} requested.`, event.tool_calls); if (event.type === "tool_started") return trace(event.round, event.tool, "RUNNING", "Executing with these arguments.", event.args, "running"); if (event.type === "tool_completed") { const result = event.event.result || {}; return trace(event.round, event.event.tool, result.error ? "ERROR" : "COMPLETE", result.error || result.status || "Result received.", { args: event.event.args, result }, result.error ? "error" : "done"); } if (event.type === "completed") { const result = event.result; trace(null, "Agent response ready", result.status === "waiting_for_user" ? "WAITING" : "ANSWERED", result.status === "waiting_for_user" ? "Awaiting user input before continuing." : "Grounded response returned."); addMessage("assistant", result.assistant_text); state.history.push({ role: "user", content: message }, { role: "assistant", content: result.assistant_text }); return; } if (event.type === "transcript_saved") return setArtifact(event.artifact); if (event.type === "error") throw new Error(event.message); }
async function boot() { setupScenarios(); $("resetButton").onclick = reset; $("composer").onsubmit = (event) => { event.preventDefault(); send($("messageInput").value); }; $("messageInput").onkeydown = (event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); send(event.currentTarget.value); } }; try { const data = await (await fetch("/api/bootstrap")).json(); setArtifact(data.artifact); const ready = data.providers.openai; $("connectionLabel").textContent = ready ? "OpenAI provider ready" : "OpenAI key missing"; if (!ready) $("connectionLabel").style.color = "#c94143"; } catch { $("connectionLabel").textContent = "Connection unavailable"; } }
boot();
